name: snippetpixie
base: core18
version: git
summary: Your little expandable snippet helper
description: |
  Save your often used snippets and then expand them whenever you type their abbreviation.
  For example:- "spr`" expands to "Snippet Pixie rules!"

grade: stable
confinement: devmode
icon: data/icons/256/com.github.bytepixie.snippetpixie.svg

apps:
  snippetpixie:
    command: desktop-launch $SNAP/usr/bin/com.github.bytepixie.snippetpixie
    plugs:
      - desktop
      - desktop-legacy
    slots: [ dbus-snippetpixie ]
    desktop: usr/share/applications/com.github.bytepixie.snippetpixie.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  dbus-snippetpixie:
    interface: dbus
    bus: session
    name: com.github.bytepixie.snippetpixie

parts:
  snippetpixie:
    after: [granite, desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: .
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=com.github.bytepixie.snippetpixie|Icon=${SNAP}/data/icons/256/com.github.bytepixie.snippetpixie.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.bytepixie.snippetpixie.desktop
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - libgee-0.8-dev
      - libsqlite3-dev
      - libgranite-dev
      - libx11-dev
      - libatspi2.0-dev
      - libibus-1.0-dev
      - libjson-glib-dev
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdbus-1-3
      - libepoxy0
      - libexpat1
      - libffi6
      - libfontconfig1
      - libgcc1
      - libgcrypt20
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgpg-error0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libblkid1
      - liblz4-1
      - liblzma5
      - libmount1
      - libpcre3
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libselinux1
      - libstdc++6
      - libsystemd0
      - libudev1
      - libuuid1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - zlib1g
      - libjson-glib-1.0-0
      - libsqlite3-0
  granite:
    plugin: cmake
    source: https://github.com/elementary/granite/archive/5.2.2.tar.gz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
    build-packages:
      - build-essential
      - libgee-0.8-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - cmake
      - gobject-introspection
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform